# Generated by Django 3.1.6 on 2021-02-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0002_auto_20210217_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='course_type',
            field=models.CharField(choices=[('A', 'Antipasto'), ('P', 'Primo'), ('S', 'Secondo'), ('Z', 'Pizza'), ('D', 'Dessert'), ('B', 'Beverage')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
