# Generated by Django 3.1.6 on 2021-03-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('course_type', models.CharField(choices=[('A', 'Antipasto'), ('P', 'Primo'), ('S', 'Secondo'), ('Z', 'Pizza'), ('D', 'Dessert'), ('B', 'Beverage'), ('Y', 'Party'), ('N', 'None')], max_length=1)),
                ('is_special', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
