# Generated by Django 3.1.6 on 2021-06-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='is_special',
        ),
    ]
