# Generated by Django 3.1.6 on 2021-02-17 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='friday_closing_time',
            field=models.TimeField(default=datetime.time(19, 45, 18, 530877)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='friday_opening_time',
            field=models.TimeField(default=datetime.time(19, 45, 18, 530872)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='monday_closing_time',
            field=models.TimeField(default=datetime.time(19, 45, 18, 530833)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='monday_opening_time',
            field=models.TimeField(default=datetime.time(19, 45, 18, 530814)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='saturday_closing_time',
            field=models.TimeField(default=datetime.time(19, 45, 18, 530888)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='saturday_opening_time',
            field=models.TimeField(default=datetime.time(19, 45, 18, 530882)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sunday_closing_time',
            field=models.TimeField(default=datetime.time(19, 45, 18, 530900)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sunday_opening_time',
            field=models.TimeField(default=datetime.time(19, 45, 18, 530893)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='thursday_closing_time',
            field=models.TimeField(default=datetime.time(19, 45, 18, 530867)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='thursday_opening_time',
            field=models.TimeField(default=datetime.time(19, 45, 18, 530862)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tuesday_closing_time',
            field=models.TimeField(default=datetime.time(19, 45, 18, 530846)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tuesday_opening_time',
            field=models.TimeField(default=datetime.time(19, 45, 18, 530840)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='wednesday_closing_time',
            field=models.TimeField(default=datetime.time(19, 45, 18, 530857)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='wednesday_opening_time',
            field=models.TimeField(default=datetime.time(19, 45, 18, 530852)),
        ),
    ]
