# Generated by Django 3.1.6 on 2021-04-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='home_delivery_available',
            field=models.BooleanField(default=True),
        ),
    ]
