# Generated by Django 3.1.6 on 2021-04-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_setting_home_delivery_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='home_delivery_cost',
            field=models.DecimalField(decimal_places=2, default=3.5, max_digits=7),
        ),
        migrations.AddField(
            model_name='setting',
            name='order_preparation_time_in_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='setting',
            name='website_available',
            field=models.BooleanField(default=True),
        ),
    ]
