# Generated by Django 3.1.6 on 2021-02-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20181220_0803'),
        ('sites', '0002_alter_domain_unique'),
        ('settings', '0003_auto_20210217_1947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
