# Generated by Django 3.1.6 on 2021-02-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='special',
            old_name='image_path',
            new_name='image',
        ),
    ]
